--
-- PostgreSQL database dump
--

\restrict fhMfo6buM6rhb2zTmmm4ucoAYlQAcBYFD6A36R4Kbwblq7pW1b3aCkeRa7XPhk0

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2026-02-02 01:58:25

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16390)
-- Name: Favorites; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Favorites" (
    "Id" integer NOT NULL,
    "ClientId" text NOT NULL,
    "PerfumeId" integer NOT NULL
);


ALTER TABLE public."Favorites" OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16389)
-- Name: Favorites_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Favorites" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Favorites_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16429)
-- Name: OrderItems; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."OrderItems" (
    "Id" integer NOT NULL,
    "PerfumeId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "UnitPrice" numeric NOT NULL,
    "OrderId" integer NOT NULL
);


ALTER TABLE public."OrderItems" OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16428)
-- Name: OrderItems_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."OrderItems" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."OrderItems_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16401)
-- Name: Orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Orders" (
    "Id" integer NOT NULL,
    "ClientId" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "TotalPrice" numeric NOT NULL
);


ALTER TABLE public."Orders" OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16400)
-- Name: Orders_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Orders" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Orders_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16413)
-- Name: Perfumes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Perfumes" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Brand" text NOT NULL,
    "Gender" text NOT NULL,
    "Season" text NOT NULL,
    "Longevity" text NOT NULL,
    "Price" numeric NOT NULL,
    "ImageUrl" text NOT NULL
);


ALTER TABLE public."Perfumes" OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16412)
-- Name: Perfumes_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Perfumes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Perfumes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5031 (class 0 OID 16390)
-- Dependencies: 220
-- Data for Name: Favorites; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Favorites" ("Id", "ClientId", "PerfumeId") FROM stdin;
\.


--
-- TOC entry 5037 (class 0 OID 16429)
-- Dependencies: 226
-- Data for Name: OrderItems; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."OrderItems" ("Id", "PerfumeId", "Quantity", "UnitPrice", "OrderId") FROM stdin;
\.


--
-- TOC entry 5033 (class 0 OID 16401)
-- Dependencies: 222
-- Data for Name: Orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Orders" ("Id", "ClientId", "CreatedAt", "TotalPrice") FROM stdin;
\.


--
-- TOC entry 5035 (class 0 OID 16413)
-- Dependencies: 224
-- Data for Name: Perfumes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Perfumes" ("Id", "Name", "Brand", "Gender", "Season", "Longevity", "Price", "ImageUrl") FROM stdin;
19	Dior Sauvage	Dior	men	all	long	95	https://cdn.paris-avenues.com/image/cache/catalog/seo50/3348901486385-550x550.jpg
20	Bleu de Chanel	Chanel	men	winter	long	120	https://orchard.vn/wp-content/uploads/2015/01/chanel-bleu-de-chanel-edp_3.jpg
21	Tom Ford Oud Wood	Tom Ford	men	fall	long	220	https://www.lookfantastic.ie/images?url=https://static.thcdn.com/productimg/original/12709312-2145154277020969.jpg
22	Acqua di Gio Profumo	Giorgio Armani	men	summer	long	135	https://tidlon.com/wp-content/uploads/2022/07/1c0edb483eb8f37a19dfd0f004a3e5ca-e1657871077664.png
23	YSL La Nuit de l’Homme	Yves Saint Laurent	men	fall	moderate	98	https://www.yslbeauty.com/dw/image/v2/BDCR_PRD/on/demandware.static/-/Sites-ysl-master-catalog/default/dw91b2cfe8/images/PACKSHOTS/FRAGRANCE/FOR_HIM/WW-50356YSL_la-nuit-de-l-homme-edp/WW-50356YSL_la-nut-de-lhomme-edp_2023_alt-view-2.jpg
24	Chanel Coco Mademoiselle	Chanel	women	all	long	130	https://dynamic.zacdn.com/S8YtQvdDcm-3fOEH_Y4c0mxoNtM=/filters:quality(70):format(webp)/https://static-hk.zacdn.com/p/chanel-3296-8819317-2.jpg
25	YSL Black Opium	Yves Saint Laurent	women	fall	long	115	https://www.yslbeautyus.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-ysl-us-Library/default/dw22c2ed6a/pdp/images/WW-51116YSL/BO%20Over%20Red%20About%20Image.jpg
26	Dior J’adore	Dior	women	spring	moderate	130	https://www.fnp.sa/cdn/shop/files/PFHR2.jpg
27	Marc Jacobs Daisy	Marc Jacobs	women	spring	moderate	95	https://i.makeup.uk/l/ln/lnsz54mhokze.jpg
28	Viktor & Rolf Flowerbomb	Viktor & Rolf	women	winter	long	150	https://www.myperfumeshop.qa/cdn/shop/products/viktor-rolf-flowerbomb-edp-perfume-for-her-263403.jpg
29	Creed Aventus	Creed	unisex	all	long	330	https://labelleperfumes.com/cdn/shop/files/creed-aventus-labelleperfumes-alt_800x.webp
30	Le Labo Santal 33	Le Labo	unisex	fall	long	192	https://orchard.vn/wp-content/uploads/2024/07/le-labo-santal-33_3.jpg
31	CK One	Calvin Klein	unisex	spring	moderate	65	https://imagescdn.simons.ca/images/21694-24301-11-A1_3/ck-one-eau-de-toilette-unisex.jpg
32	Tom Ford Black Orchid	Tom Ford	unisex	winter	long	180	https://www.beautyglobe.co.uk/cdn/shop/files/IMG-0193_421e3a77-aa26-48f6-8f99-0fe66d30636e.webp
33	Diptyque Philosykos	Diptyque	unisex	summer	moderate	130	https://www.diptyqueparis.com/media/catalog/product/o/r/original_jpg-_74a4600-modifier_9x16_2025_x_3600px_vue-alt-pdp.jpg
\.


--
-- TOC entry 5043 (class 0 OID 0)
-- Dependencies: 219
-- Name: Favorites_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Favorites_Id_seq"', 1, false);


--
-- TOC entry 5044 (class 0 OID 0)
-- Dependencies: 225
-- Name: OrderItems_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."OrderItems_Id_seq"', 1, false);


--
-- TOC entry 5045 (class 0 OID 0)
-- Dependencies: 221
-- Name: Orders_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Orders_Id_seq"', 1, false);


--
-- TOC entry 5046 (class 0 OID 0)
-- Dependencies: 223
-- Name: Perfumes_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Perfumes_Id_seq"', 33, true);


--
-- TOC entry 4872 (class 2606 OID 16399)
-- Name: Favorites PK_Favorites; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Favorites"
    ADD CONSTRAINT "PK_Favorites" PRIMARY KEY ("Id");


--
-- TOC entry 4880 (class 2606 OID 16440)
-- Name: OrderItems PK_OrderItems; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrderItems"
    ADD CONSTRAINT "PK_OrderItems" PRIMARY KEY ("Id");


--
-- TOC entry 4874 (class 2606 OID 16411)
-- Name: Orders PK_Orders; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "PK_Orders" PRIMARY KEY ("Id");


--
-- TOC entry 4876 (class 2606 OID 16427)
-- Name: Perfumes PK_Perfumes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Perfumes"
    ADD CONSTRAINT "PK_Perfumes" PRIMARY KEY ("Id");


--
-- TOC entry 4877 (class 1259 OID 16451)
-- Name: IX_OrderItems_OrderId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_OrderItems_OrderId" ON public."OrderItems" USING btree ("OrderId");


--
-- TOC entry 4878 (class 1259 OID 16452)
-- Name: IX_OrderItems_PerfumeId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_OrderItems_PerfumeId" ON public."OrderItems" USING btree ("PerfumeId");


--
-- TOC entry 4881 (class 2606 OID 16441)
-- Name: OrderItems FK_OrderItems_Orders_OrderId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrderItems"
    ADD CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES public."Orders"("Id") ON DELETE CASCADE;


--
-- TOC entry 4882 (class 2606 OID 16446)
-- Name: OrderItems FK_OrderItems_Perfumes_PerfumeId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrderItems"
    ADD CONSTRAINT "FK_OrderItems_Perfumes_PerfumeId" FOREIGN KEY ("PerfumeId") REFERENCES public."Perfumes"("Id") ON DELETE CASCADE;


-- Completed on 2026-02-02 01:58:26

--
-- PostgreSQL database dump complete
--

\unrestrict fhMfo6buM6rhb2zTmmm4ucoAYlQAcBYFD6A36R4Kbwblq7pW1b3aCkeRa7XPhk0

